### ISSUE TITLE
Use setOutput instead of exportVariable 

### ISSUE THREAD

**Issue by SvanBoxel** [umani/changed-files#1]
Hi!

Useful Action, thanks! I see you're using `exportVariable` ([GitHub docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env), [Function definition](https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L38)). 

I'm wondering whether you intended to use this instead of `setOutput` ([GitHub docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-output-parameter-set-output), [Function definition](https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L83)), as the latter seems more appropriate for the functionality you're implementing.

What are your thought?

**Comment by duarten** [comment]
Hi @SvanBoxel! 

Indeed, I think you're right and `setOutput` is more appropriate. Will fix ASAP.
