### ISSUE TITLE
Broken for filenames containing spaces

### ISSUE THREAD

**Issue by ThiefMaster** [umani/changed-files#10]
Since the list of filenames is simply joined with a space, it's impossible to get usable filenames if the repo contains a file containing spaces.

Also, the docs mention that "all output values are a single JSON encoded array", but this is not the case. It's a space-separated list...

**Comment by duarten** [comment]
I had missed this issue; sorry about that. I've pushed v3.3.0 (and v3) with a fix for this in the form of an input (`result-encoding`) which can be `string` for the current behavior, or `json` to output the list of files as a JSON encoded string.
