### ISSUE TITLE
Action only returns 30 entries. Can you add pagination support?

### ISSUE THREAD

**Issue by wushujames** [umani/changed-files#3]
Hi,

I'm using your action. It appears to only return 30 entries. Apparently that is the number of files returned in a single "page" of the `GET /repos/:owner/:repo/pulls/:pull_number/files` API you are using. https://developer.github.com/v3/pulls/#list-pull-requests-files

Is it possible to add pagination support, to get the full list of files? I tried doing it myself, but I don't really know node.js. And I tried downloading your repo and tried to figure out how to build it, but I couldn't figure it out. I got compilation errors.

Thanks!

**Comment by duarten** [comment]
Hi,

Thanks for the issue! I added pagination supported and released v3.0.1 with the fix. Could you please check if it solves your issue?

**Comment by wushujames** [comment]
It worked! I tested `changed-files` on a pull request. Previously, I could only see 30 files. With v3.0.1, I can see 38 files. So, it seems like it's working!

Thank you!
